### ISSUE TITLE
Automated deployment due to PR merge crashed the production dashboard

### ISSUE THREAD

**Issue by philippkueng** [hofratsuess/operations-dashboard#17]
The process is crashed since PR #1 for issue #3 was merged. This resulted in an 500 HTTP Status Code.

```
2016-01-12T04:13:15.914175+00:00 heroku[web.1]: State changed from crashed to starting
2016-01-12T04:13:19.815132+00:00 heroku[web.1]: Starting process with command `bundle exec thin start -R config.ru -e production -p 29320`
2016-01-12T04:13:23.281979+00:00 app[web.1]: /app/jobs/slack-integration.rb:4:in `+': no implicit conversion of nil into String (TypeError)
2016-01-12T04:13:23.281991+00:00 app[web.1]:    from /app/jobs/slack-integration.rb:4:in `<top (required)>'
2016-01-12T04:13:23.281993+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require'
2016-01-12T04:13:23.281994+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require_with_backports'
2016-01-12T04:13:23.281994+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing/app.rb:157:in `block in require_glob'
2016-01-12T04:13:23.281996+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `require_glob'
2016-01-12T04:13:23.281995+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `each'
2016-01-12T04:13:23.281996+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing/app.rb:167:in `<top (required)>'
2016-01-12T04:13:23.281997+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing.rb:3:in `require'
2016-01-12T04:13:23.281999+00:00 app[web.1]:    from config.ru:1:in `require'
2016-01-12T04:13:23.281998+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
2016-01-12T04:13:23.282001+00:00 app[web.1]:    from config.ru:1:in `block in <main>'
2016-01-12T04:13:23.282002+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
2016-01-12T04:13:23.282002+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
2016-01-12T04:13:23.282004+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
2016-01-12T04:13:23.282003+00:00 app[web.1]:    from config.ru:1:in `<main>'
2016-01-12T04:13:23.282003+00:00 app[web.1]:    from config.ru:1:in `new'
2016-01-12T04:13:23.282005+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
2016-01-12T04:13:23.282006+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
2016-01-12T04:13:23.282008+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
2016-01-12T04:13:23.282008+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
2016-01-12T04:13:23.282010+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
2016-01-12T04:13:23.282011+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
2016-01-12T04:13:23.282013+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/thin:23:in `load'
2016-01-12T04:13:23.282013+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.0.0/bin/thin:23:in `<main>'
2016-01-12T04:13:24.136625+00:00 heroku[web.1]: Process exited with status 1
2016-01-12T04:13:24.144001+00:00 heroku[web.1]: State changed from starting to crashed
```

**Definition of Done**
- [x] figure out if PR was faulty, details in the comments below
- [x] figure out if enough documentation was given in PR #1 and if general information is missing, add it to the readme according to #16

**Comment by 3deep** [comment]
- PR was fine, slack widget didn't have a valid API token, thus crashing the Ruby part of the widget, which ultimately led to the site not even loading.
- We (I) need to state, if we (I) need any config vars set.
